---
title: "gdpR: An R Package for studying differentially private algorithms"
date: "2022-11-09"
abstract: >
  An abstract of less than 150 words.
draft: true
author:  
  - name: Jordan A. Awan
    affiliation: Purdue University
    address:
    - Department of Statistics
    - West Lafayette, IN 47907
    url: https://www.britannica.com/animal/quokka
    email: jawan@purdue.edu
  - name: Kevin Eng
    affiliation: Rutgers University
    address:
    - Department of Statistics
    - Piscataway, NJ 08854
    url: https://www.britannica.com/animal/quokka
    email: ke157@stat.rutgers.edu
  - name: Robin Gong
    affiliation: Rutgers University
    address:
    - Department of Statistics
    - Piscataway, NJ 08854
    url: https://www.britannica.com/animal/quokka
    email: ruobin.gong@rutgers.edu
  - name: Nianqiao Phyllis Ju
    affiliation: Purdue University
    address:
    - Department of Statistics
    - West Lafayette, IN 47907
    url: https://www.britannica.com/animal/quokka
    email: nianqiao@purdue.edu
  - name: Vinayak A. Rao
    affiliation: Purdue University
    address:
    - Department of Statistics
    - West Lafayette, IN 47907
    url: https://www.britannica.com/animal/quokka
    email: varao@purdue.edu
type: package
output: 
  rjtools::rjournal_article:
    self_contained: yes
    toc: no
bibliography: RJreferences.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(palmerpenguins)
library(kableExtra)
```

# Introduction


# Using \CRANpkg{gdpR}

## Sampling function

The main function in the \CRANpkg{gdpR} is the `gdp_sample` function. The call
signature of the function is:

`
gdp_sample(data_model, sdp, nobs, init_par, niter = 2000, warmup = floor(niter / 2),
           chains = 1, varnames = NULL)
`

The three required inputs into `gdp_sample` function are the privacy model (`data_model`), the value
of the  observed privatized statistic (`sdp`), and the total number of observations 
in the complete data (`nobs`) [MAKE SURE NOTATION IS INTRODUCED]. The \CRANpkg{gdpR}
package is best suited for problems where the complete data can be represented in
tabular form. This is because internally, it is represented as a matrix.

The optional arguments are the number of mcmc draws (`niter`), the 
burn in period (`warmup`), number of chains (`chains`) and character
vector that names the parameters. Running multiple chains can be done in parallel
using the \CRANpkg{furrr} package. Additionally, progress can be monitored
using the \CRANpkg{progressr} package.


The `data_model` input is a `privacy`
object that can be constructed using the `new_privacy` constructor. The
process of constructing a `privacy` object will be discussed in the next section.

## Creating a `privacy` object

Creating a `privacy` object is done via the `new_privacy` function.

`
new_privacy(post_smpl = NULL, lik_smpl = NULL, ll_priv_mech = NULL,
            st_calc = NULL, add = FALSE, npar = NULL)
`

There are four functions that need to be specified.

\begin{itemize}
\item 
\end{itemize}


# Background

Some packages on interactive graphics include \CRANpkg{plotly} [@plotly] that interfaces with Javascript for web-based interactive graphics, \CRANpkg{crosstalk} [@crosstalk] that specializes cross-linking elements across individual graphics.  The recent R Journal paper \CRANpkg{tsibbletalk} [@RJ-2021-050] provides a good example of including interactive graphics into an article for the journal. It has both a set of linked plots, and also an animated gif example, illustrating linking between time series plots and feature summaries.

# Customizing tooltip design with \pkg{ToOoOlTiPs}

\pkg{ToOoOlTiPs} is a packages for customizing tooltips in interactive graphics, it features these possibilities.

# Summary

We have displayed various tooltips that are available in the package \pkg{ToOoOlTiPs}. 
